# Generated by Django 6.0.1 on 2026-02-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BypasserTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10)),
                ('test_parameter', models.CharField(default='test', help_text='Parameter name to test', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BypasserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('characters_tested', models.IntegerField(default=0)),
                ('characters_blocked', models.IntegerField(default=0)),
                ('characters_allowed', models.IntegerField(default=0)),
                ('encoding_attempts', models.IntegerField(default=0)),
                ('successful_bypasses', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bypasser.bypassertarget')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(help_text='Character being tested', max_length=10)),
                ('character_code', models.CharField(help_text='Character code (e.g., U+003C)', max_length=20)),
                ('character_name', models.CharField(help_text='Character description', max_length=100)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked'), ('error', 'Error'), ('uncertain', 'Uncertain')], max_length=20)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('response_length', models.IntegerField(blank=True, null=True)),
                ('blocked_by_waf', models.BooleanField(default=False, help_text='Appears to be blocked by WAF')),
                ('error_message', models.TextField(blank=True, help_text='Error message if blocked', null=True)),
                ('reflection_found', models.BooleanField(default=False, help_text='Character reflected in response')),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_probes', to='bypasser.bypassersession')),
            ],
            options={
                'ordering': ['character_code'],
                'unique_together': {('session', 'character')},
            },
        ),
        migrations.CreateModel(
            name='EncodingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_type', models.CharField(choices=[('url_single', 'URL Encoding (Single)'), ('url_double', 'URL Encoding (Double)'), ('url_triple', 'URL Encoding (Triple)'), ('html_decimal', 'HTML Entity (Decimal)'), ('html_hex', 'HTML Entity (Hex)'), ('unicode', 'Unicode Escape'), ('base64', 'Base64'), ('hex', 'Hexadecimal'), ('mixed_case', 'Mixed Case'), ('concatenation', 'Character Concatenation'), ('null_byte', 'Null Byte Injection'), ('comment_insertion', 'Comment Insertion'), ('utf7', 'UTF-7'), ('utf8_overlong', 'UTF-8 Overlong Encoding'), ('html5_entities', 'HTML5 Named Entities')], max_length=50)),
                ('original_payload', models.CharField(help_text='Original character/payload', max_length=500)),
                ('encoded_payload', models.CharField(help_text='Encoded version', max_length=1000)),
                ('success', models.BooleanField(default=False, help_text='Successfully bypassed filter')),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('response_length', models.IntegerField(blank=True, null=True)),
                ('bypass_confirmed', models.BooleanField(default=False, help_text='Bypass definitively confirmed')),
                ('reflection_found', models.BooleanField(default=False)),
                ('waf_triggered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('character_probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encoding_attempts', to='bypasser.characterprobe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encoding_tests', to='bypasser.bypassersession')),
            ],
            options={
                'ordering': ['-success', 'encoding_type', '-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='BypassResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_description', models.TextField(help_text='Description of the bypass technique')),
                ('payload_example', models.CharField(help_text='Example payload that worked', max_length=1000)),
                ('risk_level', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('impact_description', models.TextField(help_text='Potential security impact')),
                ('evidence', models.TextField(help_text='Evidence of successful bypass')),
                ('recommendation', models.TextField(help_text='Remediation recommendation')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bypass_results', to='bypasser.bypassersession')),
                ('character_probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bypass_results', to='bypasser.characterprobe')),
                ('encoding_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bypass_results', to='bypasser.encodingattempt')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='encodingattempt',
            index=models.Index(fields=['session', 'success'], name='bypasser_en_session_e11196_idx'),
        ),
        migrations.AddIndex(
            model_name='encodingattempt',
            index=models.Index(fields=['character_probe', 'success'], name='bypasser_en_charact_da13e5_idx'),
        ),
    ]
