# Generated by Django 6.0.1 on 2026-02-02 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bypasser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBypassTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bypass technique', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of what this technique does')),
                ('category', models.CharField(choices=[('waf', 'WAF Bypass'), ('firewall', 'Firewall Bypass'), ('ips', 'IPS Bypass'), ('ids', 'IDS Bypass'), ('filter', 'Input Filter Bypass'), ('mixed', 'Mixed/Multi-Layer Bypass')], help_text='Type of security control to bypass', max_length=20)),
                ('technique_template', models.TextField(help_text='Template with placeholders like {{payload}}, {{char}}, transformation functions')),
                ('example_input', models.CharField(blank=True, help_text='Example input', max_length=500, null=True)),
                ('example_output', models.CharField(blank=True, help_text='Example output', max_length=1000, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('author', models.CharField(blank=True, help_text='Author/creator', max_length=255, null=True)),
                ('times_used', models.IntegerField(default=0, help_text='Number of times this technique has been used')),
                ('times_successful', models.IntegerField(default=0, help_text='Number of successful bypasses')),
                ('success_rate', models.FloatField(default=0.0, help_text='Success rate percentage')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this technique is active')),
                ('is_public', models.BooleanField(default=False, help_text='Share with other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-times_successful', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='bypasser_cu_categor_97e78b_idx'), models.Index(fields=['is_active', '-times_successful'], name='bypasser_cu_is_acti_462d35_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomTechniqueExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_payload', models.CharField(help_text='Original input payload', max_length=1000)),
                ('output_payload', models.TextField(help_text='Transformed output payload')),
                ('success', models.BooleanField(default=False, help_text='Whether the bypass was successful')),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('response_length', models.IntegerField(blank=True, null=True)),
                ('bypass_confirmed', models.BooleanField(default=False, help_text='Bypass definitively confirmed')),
                ('reflection_found', models.BooleanField(default=False, help_text='Payload reflected in response')),
                ('waf_triggered', models.BooleanField(default=False, help_text='WAF/filter was triggered')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_technique_executions', to='bypasser.bypassersession')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='bypasser.custombypasstechnique')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['session', 'success'], name='bypasser_cu_session_e58d1c_idx'), models.Index(fields=['technique', 'success'], name='bypasser_cu_techniq_4d317e_idx')],
            },
        ),
    ]
