# Generated by Django 6.0.2 on 2026-02-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bypasser', '0003_readymadepayload_payloadexecution'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payloadexecution',
            new_name='bypasser_pa_session_0ec324_idx',
            old_name='bypasser_pa_session_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='payloadexecution',
            new_name='bypasser_pa_payload_4ed1b6_idx',
            old_name='bypasser_pa_payload_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='readymadepayload',
            new_name='bypasser_re_categor_667989_idx',
            old_name='bypasser_re_categor_8a7e3a_idx',
        ),
        migrations.RenameIndex(
            model_name='readymadepayload',
            new_name='bypasser_re_bypass__911d50_idx',
            old_name='bypasser_re_bypass__c5e6e0_idx',
        ),
        migrations.RenameIndex(
            model_name='readymadepayload',
            new_name='bypasser_re_risk_le_57df92_idx',
            old_name='bypasser_re_risk_le_f8b9c1_idx',
        ),
    ]
