# Generated by Django 6.0.1 on 2026-02-02 19:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObfuscationTechnique',
            fields=[
                ('technique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name of the obfuscation technique', max_length=100)),
                ('obfuscation_type', models.CharField(choices=[('name_mangling', 'Name Mangling/Renaming'), ('string_encryption', 'String Encryption'), ('control_flow', 'Control Flow Obfuscation'), ('dead_code', 'Dead Code Injection'), ('opaque_predicates', 'Opaque Predicates'), ('packing', 'Code Packing/Compression'), ('reflection', 'Reflection-based Obfuscation'), ('other', 'Other/Unknown')], max_length=30)),
                ('description', models.TextField(help_text='Description of the technique')),
                ('detection_pattern', models.TextField(blank=True, help_text='Regex or signature for detecting this technique')),
                ('deobfuscation_strategy', models.TextField(blank=True, help_text='Strategy or algorithm for defeating this technique')),
                ('common_tools', models.CharField(blank=True, help_text='Known obfuscation tools that use this technique', max_length=255)),
                ('severity', models.IntegerField(default=5, help_text='Difficulty level (1-10) of deobfuscating this technique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DecompilationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('decompiler_tool', models.CharField(help_text='Tool used for decompilation (e.g., JAD, Krakatau, JPEXS)', max_length=50)),
                ('decompiler_version', models.CharField(blank=True, max_length=50)),
                ('options', models.JSONField(blank=True, default=dict, help_text='Decompiler options and flags')),
                ('decompiled_source', models.FileField(blank=True, help_text='Archive of decompiled source code', null=True, upload_to='decompiler/source/%Y/%m/%d/')),
                ('log_output', models.TextField(blank=True, help_text='Decompilation log output')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('num_classes_found', models.IntegerField(default=0, help_text='Number of classes/modules found')),
                ('num_methods_found', models.IntegerField(default=0, help_text='Number of methods/functions found')),
                ('obfuscation_detected', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decompilation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionAnalysis',
            fields=[
                ('analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('api_endpoints', models.JSONField(blank=True, default=list, help_text='List of API endpoints the extension communicates with')),
                ('network_requests', models.JSONField(blank=True, default=list, help_text='Captured or identified network requests')),
                ('data_flows', models.JSONField(blank=True, default=list, help_text='Data flow analysis results')),
                ('vulnerabilities', models.JSONField(blank=True, default=list, help_text='List of identified security vulnerabilities')),
                ('privacy_concerns', models.JSONField(blank=True, default=list, help_text='Privacy issues (data collection, tracking, etc.)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20)),
                ('javascript_hooks', models.JSONField(blank=True, default=list, help_text='Identified JavaScript injection points for manipulation')),
                ('dom_elements', models.JSONField(blank=True, default=list, help_text='DOM elements the extension interacts with')),
                ('summary', models.TextField(blank=True, help_text='Human-readable analysis summary')),
                ('recommendations', models.TextField(blank=True, help_text='Security recommendations')),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL)),
                ('decompilation_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='decompiler.decompilationjob')),
            ],
            options={
                'verbose_name_plural': 'Extension Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionPackage',
            fields=[
                ('package_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name of the extension package', max_length=255)),
                ('extension_type', models.CharField(choices=[('java_applet', 'Java Applet (.jar/.class)'), ('flash', 'Flash/ActionScript (.swf)'), ('silverlight', 'Silverlight (.xap)'), ('javascript', 'JavaScript Extension'), ('unknown', 'Unknown Type')], default='unknown', max_length=20)),
                ('download_url', models.URLField(help_text='Original URL where the extension was captured', max_length=2048, validators=[django.core.validators.URLValidator()])),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('bytecode_file', models.FileField(help_text='Raw bytecode/package file', upload_to='decompiler/bytecode/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('checksum_md5', models.CharField(blank=True, max_length=32)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('downloaded', 'Downloaded'), ('pending_analysis', 'Pending Analysis'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='downloaded', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this package')),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddField(
            model_name='decompilationjob',
            name='extension_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decompilation_jobs', to='decompiler.extensionpackage'),
        ),
        migrations.CreateModel(
            name='DetectedObfuscation',
            fields=[
                ('detection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0.0-1.0) that this technique is present')),
                ('evidence', models.TextField(blank=True, help_text='Code snippets or patterns that triggered detection')),
                ('location', models.CharField(blank=True, help_text='File/class/method where technique was detected', max_length=512)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('deobfuscated', models.BooleanField(default=False, help_text='Whether deobfuscation was attempted')),
                ('deobfuscation_success', models.BooleanField(default=False)),
                ('decompilation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_obfuscations', to='decompiler.decompilationjob')),
                ('obfuscation_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='decompiler.obfuscationtechnique')),
            ],
            options={
                'ordering': ['-confidence_score', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficInterception',
            fields=[
                ('interception_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('websocket', 'WebSocket'), ('amf', 'Action Message Format (AMF)'), ('java_serialization', 'Java Serialization'), ('custom', 'Custom Protocol')], max_length=30)),
                ('request_url', models.URLField(max_length=2048)),
                ('request_method', models.CharField(default='GET', max_length=10)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.BinaryField(blank=True, help_text='Raw request body')),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.BinaryField(blank=True, help_text='Raw response body')),
                ('is_serialized', models.BooleanField(default=False)),
                ('serialization_format', models.CharField(blank=True, max_length=50)),
                ('deserialized_data', models.JSONField(blank=True, default=dict, help_text='Deserialized/parsed data')),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('extension_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intercepted_traffic', to='decompiler.extensionpackage')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='extensionpackage',
            index=models.Index(fields=['extension_type', 'status'], name='decompiler__extensi_e9585e_idx'),
        ),
        migrations.AddIndex(
            model_name='extensionpackage',
            index=models.Index(fields=['downloaded_at'], name='decompiler__downloa_4390d3_idx'),
        ),
        migrations.AddIndex(
            model_name='decompilationjob',
            index=models.Index(fields=['status', 'created_at'], name='decompiler__status_5a5faa_idx'),
        ),
        migrations.AddIndex(
            model_name='decompilationjob',
            index=models.Index(fields=['extension_package', 'status'], name='decompiler__extensi_f22bf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detectedobfuscation',
            unique_together={('decompilation_job', 'obfuscation_technique', 'location')},
        ),
        migrations.AddIndex(
            model_name='trafficinterception',
            index=models.Index(fields=['extension_package', 'timestamp'], name='decompiler__extensi_adc61d_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficinterception',
            index=models.Index(fields=['protocol', 'timestamp'], name='decompiler__protoco_05821d_idx'),
        ),
    ]
