# Generated by Django 6.0.2 on 2026-02-26 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decompiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecompilerTool',
            fields=[
                ('tool_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('executable_path', models.CharField(blank=True, max_length=512)),
                ('is_available', models.BooleanField(default=False)),
                ('supported_types', models.JSONField(blank=True, default=list, help_text='List of extension types this tool can handle')),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='extensionpackage',
            name='extension_type',
            field=models.CharField(choices=[('chrome_crx', 'Chrome Extension (.crx)'), ('firefox_xpi', 'Firefox Extension (.xpi)'), ('edge_msix', 'Edge Extension (.msix)'), ('safari_appex', 'Safari App Extension'), ('webextension', 'Generic WebExtension (manifest.json)'), ('electron_asar', 'Electron ASAR Package'), ('wasm', 'WebAssembly Module (.wasm)'), ('pwa', 'Progressive Web App'), ('java_applet', 'Java Applet (.jar/.class)'), ('flash', 'Flash/ActionScript (.swf)'), ('silverlight', 'Silverlight (.xap)'), ('javascript', 'JavaScript Extension'), ('browser_addon', 'Generic Browser Add-on'), ('userscript', 'Userscript (Tampermonkey/Greasemonkey)'), ('unknown', 'Unknown Type')], default='unknown', max_length=30),
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('snippet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('snippet_type', models.CharField(choices=[('vulnerability', 'Vulnerability'), ('secret', 'Hardcoded Secret'), ('api_call', 'API Call'), ('network_request', 'Network Request'), ('obfuscation', 'Obfuscation'), ('malicious', 'Malicious Pattern'), ('interesting', 'Interesting Code')], max_length=30)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('code', models.TextField()),
                ('context', models.TextField(blank=True, help_text='Surrounding code for context')),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('decompilation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='decompiler.decompilationjob')),
            ],
            options={
                'ordering': ['-found_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionManifest',
            fields=[
                ('manifest_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('manifest_version', models.IntegerField(blank=True, help_text='Manifest version (2 or 3 for WebExtensions)', null=True)),
                ('manifest_type', models.CharField(blank=True, help_text='manifest.json, install.rdf, Info.plist', max_length=50)),
                ('raw_manifest', models.JSONField(blank=True, default=dict)),
                ('extension_name', models.CharField(blank=True, max_length=255)),
                ('extension_version', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('homepage_url', models.URLField(blank=True, max_length=2048)),
                ('background_scripts', models.JSONField(blank=True, default=list)),
                ('content_scripts', models.JSONField(blank=True, default=list)),
                ('web_accessible_resources', models.JSONField(blank=True, default=list)),
                ('content_security_policy', models.TextField(blank=True)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('extension_package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifest', to='decompiler.extensionpackage')),
            ],
            options={
                'verbose_name_plural': 'Extension Manifests',
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityFinding',
            fields=[
                ('finding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('cvss_score', models.FloatField(blank=True, help_text='CVSS score 0.0-10.0', null=True)),
                ('cwe_id', models.CharField(blank=True, help_text='CWE identifier (e.g. CWE-79)', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('false_positive', models.BooleanField(default=False)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_findings', to='decompiler.extensionanalysis')),
            ],
            options={
                'ordering': ['-cvss_score', '-found_at'],
            },
        ),
        migrations.CreateModel(
            name='DecompilationArtifact',
            fields=[
                ('artifact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('artifact_type', models.CharField(choices=[('source', 'Source Code File'), ('resource', 'Resource File'), ('config', 'Configuration File'), ('manifest', 'Manifest File'), ('source_map', 'Source Map'), ('other', 'Other')], default='source', max_length=20)),
                ('file_path', models.CharField(help_text='Relative path within decompiled output', max_length=512)),
                ('file_size', models.BigIntegerField(default=0)),
                ('language', models.CharField(blank=True, help_text='Programming language (java, javascript, csharp, etc.)', max_length=50)),
                ('content', models.TextField(blank=True, help_text='File content (for text files)')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decompilation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='decompiler.decompilationjob')),
            ],
            options={
                'ordering': ['file_path'],
                'unique_together': {('decompilation_job', 'file_path')},
            },
        ),
        migrations.CreateModel(
            name='ExtensionPermission',
            fields=[
                ('permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('permission_name', models.CharField(max_length=255)),
                ('permission_type', models.CharField(blank=True, help_text='api, host, content_script, etc.', max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score 0-100')),
                ('description', models.TextField(blank=True)),
                ('is_used', models.BooleanField(blank=True, help_text='Whether the permission is actually used in code', null=True)),
                ('extension_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='decompiler.extensionpackage')),
            ],
            options={
                'ordering': ['-risk_score', 'permission_name'],
                'unique_together': {('extension_package', 'permission_name')},
            },
        ),
    ]
