# Generated by Django 6.0.2 on 2026-02-03 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('host_discovered', models.BooleanField(default=False)),
                ('open_ports_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('raw_output', models.TextField(blank=True, help_text='Raw scan output')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StealthConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('timing_template', models.IntegerField(default=3, help_text='0=Paranoid, 1=Sneaky, 2=Polite, 3=Normal, 4=Aggressive, 5=Insane')),
                ('scan_delay', models.FloatField(default=0, help_text='Delay between probes in seconds')),
                ('max_scan_delay', models.FloatField(default=0, help_text='Maximum delay between probes')),
                ('min_rate', models.IntegerField(default=0, help_text='Minimum packets per second')),
                ('max_rate', models.IntegerField(default=0, help_text='Maximum packets per second')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum probe retransmissions')),
                ('host_timeout', models.IntegerField(default=900, help_text='Timeout per host in seconds')),
                ('fragment_packets', models.BooleanField(default=False, help_text='Fragment IP packets')),
                ('randomize_hosts', models.BooleanField(default=True, help_text='Randomize target host order')),
                ('spoof_mac', models.BooleanField(default=False, help_text='Spoof MAC address')),
                ('decoy_scanning', models.BooleanField(default=False, help_text='Use decoy IP addresses')),
                ('data_length', models.IntegerField(default=0, help_text='Append random data to packets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filtered', 'Filtered'), ('unfiltered', 'Unfiltered'), ('open|filtered', 'Open|Filtered'), ('closed|filtered', 'Closed|Filtered')], max_length=20)),
                ('scan_type', models.CharField(choices=[('syn', 'TCP SYN (Stealth)'), ('connect', 'TCP Connect'), ('ack', 'TCP ACK'), ('window', 'TCP Window'), ('maimon', 'TCP Maimon'), ('null', 'TCP NULL'), ('fin', 'TCP FIN'), ('xmas', 'TCP XMAS'), ('udp', 'UDP')], default='syn', max_length=20)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_scans', to='data_tracer.scanresult')),
            ],
            options={
                'ordering': ['port'],
            },
        ),
        migrations.CreateModel(
            name='PacketCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packet_type', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('arp', 'ARP'), ('other', 'Other')], max_length=10)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('packet_size', models.IntegerField()),
                ('payload', models.BinaryField(blank=True)),
                ('flags', models.CharField(blank=True, max_length=50)),
                ('relevance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='medium', max_length=10)),
                ('analysis_notes', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_captures', to='data_tracer.scanresult')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='OSFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('os_name', models.CharField(max_length=200)),
                ('os_family', models.CharField(blank=True, max_length=100)),
                ('os_generation', models.CharField(blank=True, max_length=100)),
                ('os_vendor', models.CharField(blank=True, max_length=100)),
                ('accuracy', models.IntegerField(default=0, help_text='Accuracy percentage 0-100')),
                ('cpe', models.CharField(blank=True, max_length=500)),
                ('fingerprint_method', models.CharField(default='tcp_ip_stack', max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_fingerprints', to='data_tracer.scanresult')),
            ],
            options={
                'ordering': ['-accuracy', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(help_text='IP address, hostname, or network range', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scan_type', models.CharField(default='comprehensive', max_length=50)),
                ('stealth_mode', models.BooleanField(default=False, help_text='Enable stealth scanning techniques')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scanresult',
            name='scan_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='data_tracer.scantarget'),
        ),
        migrations.CreateModel(
            name='ServiceDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('service_version', models.CharField(blank=True, max_length=200)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('extrainfo', models.TextField(blank=True)),
                ('confidence', models.IntegerField(default=0, help_text='Confidence level 0-100')),
                ('cpe', models.CharField(blank=True, help_text='Common Platform Enumeration', max_length=500)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('port_scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_detection', to='data_tracer.portscan')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data_tracer.scanresult')),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['scan_result', 'logged_at'], name='data_tracer_scan_re_f3f174_idx'), models.Index(fields=['level'], name='data_tracer_level_ef0714_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='portscan',
            index=models.Index(fields=['scan_result', 'port'], name='data_tracer_scan_re_c59f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='portscan',
            index=models.Index(fields=['state'], name='data_tracer_state_6c177d_idx'),
        ),
        migrations.AddIndex(
            model_name='packetcapture',
            index=models.Index(fields=['scan_result', 'captured_at'], name='data_tracer_scan_re_c2f76e_idx'),
        ),
        migrations.AddIndex(
            model_name='packetcapture',
            index=models.Index(fields=['relevance'], name='data_tracer_relevan_502078_idx'),
        ),
        migrations.AddIndex(
            model_name='packetcapture',
            index=models.Index(fields=['packet_type'], name='data_tracer_packet__3d5a82_idx'),
        ),
        migrations.AddIndex(
            model_name='scantarget',
            index=models.Index(fields=['status', 'created_at'], name='data_tracer_status_ab0a93_idx'),
        ),
        migrations.AddIndex(
            model_name='scantarget',
            index=models.Index(fields=['created_by', 'created_at'], name='data_tracer_created_d61fdd_idx'),
        ),
    ]
