# Generated by Django 6.0.1 on 2026-02-03 13:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQLInjectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(db_index=True, help_text='Target URL to test for SQL injection', max_length=2048)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', help_text='HTTP method to use', max_length=10)),
                ('get_params', models.JSONField(blank=True, help_text='GET parameters as JSON object', null=True)),
                ('post_params', models.JSONField(blank=True, help_text='POST parameters as JSON object', null=True)),
                ('cookies', models.JSONField(blank=True, help_text='Cookies as JSON object', null=True)),
                ('headers', models.JSONField(blank=True, help_text='Custom headers as JSON object', null=True)),
                ('enable_error_based', models.BooleanField(default=True, help_text='Enable error-based SQL injection detection')),
                ('enable_time_based', models.BooleanField(default=True, help_text='Enable time-based (blind) SQL injection detection')),
                ('enable_exploitation', models.BooleanField(default=True, help_text='Attempt exploitation if vulnerability found')),
                ('use_random_delays', models.BooleanField(default=False, help_text='Use random delays between requests')),
                ('min_delay', models.FloatField(default=0.5, help_text='Minimum delay in seconds')),
                ('max_delay', models.FloatField(default=2.0, help_text='Maximum delay in seconds')),
                ('randomize_user_agent', models.BooleanField(default=True, help_text='Use randomized User-Agent headers')),
                ('use_payload_obfuscation', models.BooleanField(default=False, help_text='Obfuscate payloads to evade WAF')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vulnerabilities_found', models.IntegerField(default=0, help_text='Number of vulnerabilities found')),
                ('error_message', models.TextField(blank=True, help_text='Error message if task failed')),
            ],
            options={
                'verbose_name': 'SQL Injection Task',
                'verbose_name_plural': 'SQL Injection Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sql_attacke_status_1f101b_idx'), models.Index(fields=['target_url', 'status'], name='sql_attacke_target__3d767b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SQLInjectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injection_type', models.CharField(choices=[('error_based', 'Error-based'), ('time_based', 'Time-based (Blind)'), ('union_based', 'UNION-based'), ('boolean_based', 'Boolean-based'), ('stacked_queries', 'Stacked Queries')], db_index=True, help_text='Type of SQL injection detected', max_length=50)),
                ('vulnerable_parameter', models.CharField(help_text='Name of the vulnerable parameter', max_length=255)),
                ('parameter_type', models.CharField(help_text='Type: GET, POST, COOKIE, HEADER', max_length=20)),
                ('test_payload', models.TextField(help_text='Payload used to detect the vulnerability')),
                ('detection_evidence', models.TextField(help_text='Evidence that confirms the vulnerability')),
                ('request_data', models.JSONField(blank=True, help_text='Full request details as JSON', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response details as JSON', null=True)),
                ('is_exploitable', models.BooleanField(default=False, help_text='Whether exploitation was successful')),
                ('database_type', models.CharField(blank=True, help_text='Detected database type (MySQL, PostgreSQL, etc.)', max_length=50)),
                ('database_version', models.CharField(blank=True, help_text='Database version if extracted', max_length=100)),
                ('current_database', models.CharField(blank=True, help_text='Current database name if extracted', max_length=100)),
                ('current_user', models.CharField(blank=True, help_text='Database user if extracted', max_length=100)),
                ('extracted_tables', models.JSONField(blank=True, help_text='List of extracted table names', null=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='Sample extracted data', null=True)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('severity', models.CharField(default='critical', help_text='Severity: critical, high, medium, low', max_length=20)),
                ('task', models.ForeignKey(help_text='The attack task this result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sql_attacker.sqlinjectiontask')),
            ],
            options={
                'verbose_name': 'SQL Injection Result',
                'verbose_name_plural': 'SQL Injection Results',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['task', 'injection_type'], name='sql_attacke_task_id_91fd01_idx'), models.Index(fields=['severity', 'detected_at'], name='sql_attacke_severit_756ab5_idx')],
            },
        ),
    ]
