# Generated by Django 6.0.2 on 2026-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_attacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='discovered_params',
            field=models.JSONField(blank=True, help_text='All discovered parameters from target page', null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='parameter_source',
            field=models.CharField(default='manual', help_text='Source: manual, form, hidden, link, url, js', max_length=20),
        ),
        migrations.AddField(
            model_name='sqlinjectiontask',
            name='auto_discover_params',
            field=models.BooleanField(default=True, help_text='Automatically discover parameters from target page'),
        ),
        migrations.AddField(
            model_name='sqlinjectiontask',
            name='discovered_params',
            field=models.JSONField(blank=True, help_text='Parameters discovered during attack', null=True),
        ),
    ]
