# Generated by Django 6.0.2 on 2026-02-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_attacker', '0002_sqlinjectionresult_discovered_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlinjectionresult',
            name='discovered_params',
        ),
    ]
