# Generated by Django 6.0 on 2026-02-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_attacker', '0005_stealth_and_interactive_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlinjectiontask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=21),
        ),
    ]
