# Generated by Django 6.0.2 on 2026-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_attacker', '0006_alter_sqlinjectiontask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlinjectionresult',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Injection Attack Result', 'verbose_name_plural': 'Injection Attack Results'},
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='all_injection_points',
            field=models.JSONField(blank=True, help_text='All discovered injection points', null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='evidence_timeline',
            field=models.JSONField(blank=True, help_text='Timeline of attack steps', null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='extracted_sensitive_data',
            field=models.JSONField(blank=True, help_text='Categorized extracted data', null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='gif_evidence',
            field=models.FileField(blank=True, null=True, upload_to='sql_attacker/gifs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='injection_context',
            field=models.CharField(choices=[('sql', 'SQL'), ('ldap', 'LDAP'), ('xpath', 'XPath'), ('message_queue', 'Message Queue'), ('custom_query', 'Custom Query Language')], db_index=True, default='sql', help_text='Injection context type (SQL, LDAP, XPath, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='proof_of_impact',
            field=models.TextField(blank=True, help_text='Evidence of real-world impact', null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='screenshots',
            field=models.JSONField(blank=True, help_text='Array of screenshot paths', null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='successful_payloads',
            field=models.JSONField(blank=True, help_text='All successful payloads by type', null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='verified',
            field=models.BooleanField(default=False, help_text='Verified through successful exploitation'),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='video_evidence',
            field=models.FileField(blank=True, null=True, upload_to='sql_attacker/videos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='visual_proof_path',
            field=models.CharField(blank=True, help_text='Path to screenshot or GIF showing exploitation impact', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='visual_proof_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='visual_proof_type',
            field=models.CharField(blank=True, choices=[('screenshot', 'Screenshot'), ('gif', 'Animated GIF'), ('video', 'Video')], help_text='Type of visual proof', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='sqlinjectionresult',
            index=models.Index(fields=['injection_context', 'detected_at'], name='sql_attacke_injecti_88412f_idx'),
        ),
    ]
