# Generated by Django 6.0.2 on 2026-02-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_attacker', '0008_fix_visual_evidence_fields_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='confidence_rationale',
            field=models.TextField(blank=True, default='', help_text='Human-readable explanation of how the confidence score was reached'),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='evidence_packet',
            field=models.JSONField(blank=True, help_text='Structured evidence: normalized diff summary, matched patterns, classifier outcome, timing delta', null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='injection_location',
            field=models.CharField(blank=True, default='', help_text='Where the injection point was found: GET, POST, header, cookie, json', max_length=20),
        ),
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='reproduction_steps',
            field=models.TextField(blank=True, default='', help_text='Safe, step-by-step instructions to reproduce the finding'),
        ),
    ]
