# Generated by Django 6.0.2 on 2026-02-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_attacker', '0009_add_finding_schema_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='union_poc_html',
            field=models.TextField(blank=True, help_text='HTML evidence table generated by the union-based SQL injection PoC module. Proof-of-concept only – non-destructive (SELECT/UNION payloads only).', null=True),
        ),
    ]
