# Generated by Django 6.0.2 on 2026-02-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_attacker', '0010_add_union_poc_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlinjectionresult',
            name='oob_findings',
            field=models.JSONField(blank=True, help_text='OOB payloads generated for this finding. Each entry contains technique, payload (redacted to first 200 chars), listener_type, and requires_privileges.', null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectiontask',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for the background worker job', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sqlinjectiontask',
            name='enable_oob',
            field=models.BooleanField(default=True, help_text='Enable OOB payload generation (requires oob_attacker_host to attempt callbacks)'),
        ),
        migrations.AddField(
            model_name='sqlinjectiontask',
            name='oob_attacker_host',
            field=models.CharField(blank=True, default='', help_text='Attacker-controlled hostname/IP for OOB callbacks (e.g. burpcollaborator.net subdomain)', max_length=255),
        ),
        migrations.AddField(
            model_name='sqlinjectiontask',
            name='oob_exfil_expression',
            field=models.CharField(blank=True, default='', help_text='SQL expression to exfiltrate via OOB (e.g. @@version, user). Leave blank to use the safe per-DB default (user/version).', max_length=255),
        ),
        migrations.AddField(
            model_name='sqlinjectiontask',
            name='oob_max_payloads',
            field=models.IntegerField(default=5, help_text='Maximum number of OOB payloads to attempt per task (rate-limiting cap)'),
        ),
        migrations.AddField(
            model_name='sqlinjectiontask',
            name='oob_max_retries',
            field=models.IntegerField(default=2, help_text='Maximum retry attempts per OOB payload'),
        ),
    ]
