# Generated by Django 6.0.1 on 2026-02-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('http', 'HTTP Request'), ('dns', 'DNS Query'), ('smtp', 'SMTP Connection'), ('other', 'Other')], max_length=20)),
                ('source_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.TextField()),
                ('http_method', models.CharField(blank=True, max_length=10, null=True)),
                ('http_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('http_headers', models.TextField(blank=True, null=True)),
                ('http_body', models.TextField(blank=True, null=True)),
                ('dns_query_type', models.CharField(blank=True, max_length=20, null=True)),
                ('dns_query_name', models.CharField(blank=True, max_length=255, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='collaborator.collaboratorserver')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='collaborato_timesta_3ab520_idx'), models.Index(fields=['interaction_type'], name='collaborato_interac_321abc_idx'), models.Index(fields=['source_ip'], name='collaborato_source__f112d4_idx')],
            },
        ),
    ]
