# Generated by Django 6.0.2 on 2026-02-05 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('icon', models.CharField(default='🔧', max_length=50)),
                ('category', models.CharField(default='security', max_length=50)),
                ('capabilities', models.TextField(help_text='Comma-separated list of capabilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='app_manager.appconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='AppStateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_state', models.BooleanField()),
                ('new_state', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('app_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='app_manager.appconfiguration')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
