# Generated by Django 6.0.2 on 2026-02-13 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProxyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_enabled', models.BooleanField(default=False, help_text='Enable proxy authentication')),
                ('auth_username', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_password', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=512, null=True)),
                ('ip_whitelist', models.TextField(blank=True, help_text='Comma-separated list of allowed IPs', null=True)),
                ('ip_blacklist', models.TextField(blank=True, help_text='Comma-separated list of blocked IPs', null=True)),
                ('logging_enabled', models.BooleanField(default=True)),
                ('log_request_body', models.BooleanField(default=True)),
                ('log_response_body', models.BooleanField(default=True)),
                ('log_directory', models.CharField(default='logs/proxy', max_length=512)),
                ('connection_timeout', models.IntegerField(default=30, help_text='Connection timeout in seconds')),
                ('transfer_timeout', models.IntegerField(default=300, help_text='Transfer timeout in seconds')),
                ('max_concurrent_clients', models.IntegerField(default=100)),
                ('cache_enabled', models.BooleanField(default=False)),
                ('websocket_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxy Configuration',
                'verbose_name_plural': 'Proxy Configurations',
            },
        ),
        migrations.CreateModel(
            name='ProxyError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('CONNECTION_RESET', 'Connection Reset'), ('TIMEOUT', 'Timeout'), ('AUTH_FAILURE', 'Authentication Failure'), ('PROTOCOL_ERROR', 'Protocol Error'), ('SSL_ERROR', 'SSL/TLS Error'), ('DNS_ERROR', 'DNS Resolution Error'), ('OTHER', 'Other Error')], max_length=50)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebSocketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(help_text='Unique WebSocket connection identifier', max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('direction', models.CharField(choices=[('SEND', 'Client to Server'), ('RECEIVE', 'Server to Client')], max_length=10)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('BINARY', 'Binary'), ('PING', 'Ping'), ('PONG', 'Pong'), ('CLOSE', 'Close')], max_length=20)),
                ('payload', models.TextField()),
                ('payload_size', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='proxyrequest',
            name='auth_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxyrequest',
            name='auth_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxyrequest',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proxyrequest',
            name='is_replay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxyrequest',
            name='original_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to='proxy.proxyrequest'),
        ),
        migrations.AddField(
            model_name='proxyrequest',
            name='protocol',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('WS', 'WebSocket'), ('WSS', 'Secure WebSocket')], default='HTTP', max_length=10),
        ),
        migrations.AddField(
            model_name='proxyrequest',
            name='request_size',
            field=models.IntegerField(default=0, help_text='Request size in bytes'),
        ),
        migrations.AddField(
            model_name='proxyrequest',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True),
        ),
        migrations.AddField(
            model_name='proxyrequest',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='proxyresponse',
            name='cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxyresponse',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxyresponse',
            name='response_size',
            field=models.IntegerField(default=0, help_text='Response size in bytes'),
        ),
        migrations.AddIndex(
            model_name='proxyrequest',
            index=models.Index(fields=['-timestamp'], name='proxy_proxy_timesta_634588_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyrequest',
            index=models.Index(fields=['source_ip'], name='proxy_proxy_source__ef7d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyrequest',
            index=models.Index(fields=['method'], name='proxy_proxy_method_1ac3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyrequest',
            index=models.Index(fields=['protocol'], name='proxy_proxy_protoco_f2692c_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyresponse',
            index=models.Index(fields=['status_code'], name='proxy_proxy_status__4e67d2_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['source_ip', '-timestamp'], name='proxy_authe_source__498f25_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['-timestamp'], name='proxy_authe_timesta_d5db5b_idx'),
        ),
        migrations.AddField(
            model_name='proxyerror',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='proxy.proxyrequest'),
        ),
        migrations.AddIndex(
            model_name='websocketmessage',
            index=models.Index(fields=['connection_id', '-timestamp'], name='proxy_webso_connect_115bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='websocketmessage',
            index=models.Index(fields=['-timestamp'], name='proxy_webso_timesta_d5284c_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyerror',
            index=models.Index(fields=['-timestamp'], name='proxy_proxy_timesta_006b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyerror',
            index=models.Index(fields=['error_type'], name='proxy_proxy_error_t_9137c4_idx'),
        ),
    ]
