# Generated by Django 6.0.2 on 2026-02-03 22:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncodingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Encoding name (e.g., URL Encode, Base64)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='How this encoding works')),
                ('encoding_type', models.CharField(help_text='Type: url, base64, hex, unicode, etc.', max_length=50)),
                ('is_reversible', models.BooleanField(default=True, help_text='Can be decoded back to original')),
            ],
            options={
                'verbose_name': 'Encoding Technique',
                'verbose_name_plural': 'Encoding Techniques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Payload name/identifier', max_length=200)),
                ('payload_text', models.TextField(help_text='The actual payload code/string')),
                ('description', models.TextField(blank=True, help_text='What this payload does and how it works')),
                ('is_obfuscated', models.BooleanField(default=False, help_text='Whether payload is obfuscated')),
                ('bypass_technique', models.CharField(blank=True, help_text='Bypass technique used (e.g., WAF bypass)', max_length=100)),
                ('platform', models.CharField(blank=True, help_text='Target platform (e.g., Windows, Linux, Web)', max_length=100)),
                ('is_custom', models.BooleanField(default=False, help_text='User-submitted vs pre-loaded')),
                ('submitted_by', models.CharField(blank=True, help_text='User who submitted this payload', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success_rate', models.IntegerField(default=0, help_text='Success rate percentage (0-100)')),
            ],
            options={
                'verbose_name': 'Payload',
                'verbose_name_plural': 'Payloads',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Vulnerability name (e.g., XSS, SQLi, LFI)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the vulnerability')),
                ('category', models.CharField(db_index=True, help_text='Category: injection, misconfiguration, etc.', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Vulnerability Type',
                'verbose_name_plural': 'Vulnerability Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CraftedPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crafted_text', models.TextField(help_text='Final crafted/encoded payload')),
                ('encodings_applied', models.JSONField(default=list, help_text='List of encoding techniques applied')),
                ('manipulations_applied', models.JSONField(default=list, help_text='List of manipulation tricks applied')),
                ('tested', models.BooleanField(default=False, help_text='Has been tested')),
                ('successful', models.BooleanField(default=False, help_text='Test was successful')),
                ('test_notes', models.TextField(blank=True, help_text='Notes from testing')),
                ('test_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('base_payload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafted_versions', to='manipulator.payload')),
            ],
            options={
                'verbose_name': 'Crafted Payload',
                'verbose_name_plural': 'Crafted Payloads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayloadManipulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Trick name', max_length=200)),
                ('technique', models.TextField(help_text='The manipulation technique/pattern')),
                ('description', models.TextField(help_text='Explanation of the bypass technique')),
                ('example', models.TextField(blank=True, help_text='Example usage')),
                ('effectiveness', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('target_defense', models.CharField(blank=True, help_text='What defense this bypasses (e.g., WAF, filter)', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manipulation_tricks', to='manipulator.vulnerabilitytype')),
            ],
            options={
                'verbose_name': 'Payload Manipulation',
                'verbose_name_plural': 'Payload Manipulations',
                'ordering': ['-effectiveness', 'name'],
            },
        ),
        migrations.AddField(
            model_name='payload',
            name='vulnerability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='manipulator.vulnerabilitytype'),
        ),
        migrations.AddIndex(
            model_name='payload',
            index=models.Index(fields=['vulnerability', 'created_at'], name='manipulator_vulnera_c94951_idx'),
        ),
        migrations.AddIndex(
            model_name='payload',
            index=models.Index(fields=['is_custom', 'vulnerability'], name='manipulator_is_cust_e05f90_idx'),
        ),
    ]
