# Generated by Django 6.0.2 on 2026-02-26 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_url', models.URLField()),
                ('target_scope', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('injecting', 'Injecting'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mode', models.CharField(choices=[('auto', 'Fully Automatic'), ('semi', 'Semi-Automatic'), ('manual', 'Manual Payloads Only')], default='auto', max_length=20)),
                ('concurrency', models.IntegerField(default=10)),
                ('follow_redirects', models.BooleanField(default=True)),
                ('max_depth', models.IntegerField(default=5)),
                ('include_headers', models.BooleanField(default=True)),
                ('include_cookies', models.BooleanField(default=True)),
                ('custom_headers', models.JSONField(default=dict)),
                ('authentication', models.JSONField(default=dict)),
                ('use_builtin_payloads', models.BooleanField(default=True)),
                ('use_custom_payloads', models.BooleanField(default=True)),
                ('custom_payload_text', models.TextField(blank=True)),
                ('vuln_types_to_test', models.JSONField(default=list)),
                ('manipulation_level', models.CharField(choices=[('minimal', 'Minimal'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive'), ('maximum', 'Maximum')], default='moderate', max_length=20)),
                ('total_injection_points', models.IntegerField(default=0)),
                ('total_payloads_tested', models.IntegerField(default=0)),
                ('total_requests_sent', models.IntegerField(default=0)),
                ('successful_exploits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredInjectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('parameter_name', models.CharField(max_length=500)),
                ('parameter_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('header', 'Header'), ('cookie', 'Cookie'), ('json', 'JSON'), ('xml', 'XML'), ('file', 'File'), ('websocket', 'WebSocket')], max_length=20)),
                ('injection_location', models.CharField(blank=True, max_length=200)),
                ('original_value', models.TextField(blank=True)),
                ('form_action', models.URLField(blank=True, max_length=2000)),
                ('form_method', models.CharField(blank=True, max_length=10)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injection_points', to='manipulator.attackcampaign')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='InjectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_text', models.TextField()),
                ('manipulations_applied', models.JSONField(default=list)),
                ('encodings_applied', models.JSONField(default=list)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.URLField(max_length=2000)),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('vulnerability_type', models.CharField(blank=True, max_length=100)),
                ('detection_method', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence', models.TextField(blank=True)),
                ('poc_curl_command', models.TextField(blank=True)),
                ('poc_python_script', models.TextField(blank=True)),
                ('poc_report', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='info', max_length=20)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='manipulator.attackcampaign')),
                ('injection_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manipulator.discoveredinjectionpoint')),
                ('payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manipulator.payload')),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='PayloadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('builtin', 'Built-in'), ('user', 'User Provided'), ('discovered', 'Auto-Discovered'), ('imported', 'Imported')], max_length=20)),
                ('payloads_text', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('effectiveness_score', models.FloatField(default=0.0)),
                ('times_used', models.IntegerField(default=0)),
                ('times_successful', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vulnerability_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manipulator.vulnerabilitytype')),
            ],
            options={
                'ordering': ['-effectiveness_score', '-times_successful'],
            },
        ),
    ]
