# Generated by Django 6.0.2 on 2026-02-16 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='forensics/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('md5_hash', models.CharField(blank=True, max_length=32)),
                ('device_model', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('hex_sample', models.TextField(blank=True, help_text='First 256 bytes in hex format')),
                ('analysis_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Forensic File',
                'verbose_name_plural': 'Forensic Files',
                'ordering': ['-upload_date'],
            },
        ),
    ]
