# Generated by Django 6.0.1 on 2026-02-02 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterceptedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('original_method', models.CharField(max_length=10)),
                ('original_headers', models.TextField()),
                ('original_body', models.TextField(blank=True, null=True)),
                ('modified_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('modified_method', models.CharField(blank=True, max_length=10, null=True)),
                ('modified_headers', models.TextField(blank=True, null=True)),
                ('modified_body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('modified', 'Modified'), ('forwarded', 'Forwarded'), ('dropped', 'Dropped')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('proxy_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy.proxyrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
