# Generated by Django 6.0.2 on 2026-02-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interceptor', '0003_update_interceptor_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='interceptedrequest',
            new_name='interceptor_timesta_505c0a_idx',
            old_name='interceptor_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='interceptedrequest',
            new_name='interceptor_source__a09f0d_idx',
            old_name='interceptor_sourcea_idx',
        ),
        migrations.RenameIndex(
            model_name='interceptedrequest',
            new_name='interceptor_method_43698d_idx',
            old_name='interceptor_method_idx',
        ),
        migrations.RenameIndex(
            model_name='interceptedresponse',
            new_name='interceptor_status__7bd073_idx',
            old_name='interceptor_statusc_idx',
        ),
        migrations.RenameIndex(
            model_name='payloadrule',
            new_name='interceptor_active_0fe96c_idx',
            old_name='interceptor_active_idx',
        ),
        migrations.AlterField(
            model_name='interceptedrequest',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interceptedrequest',
            name='headers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='interceptedrequest',
            name='source_app',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
