# Generated by Django 6.0.1 on 2026-02-02 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanner.scantarget')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_type', models.CharField(choices=[('xss', 'Cross-Site Scripting (XSS)'), ('sqli', 'SQL Injection'), ('csrf', 'Cross-Site Request Forgery'), ('xxe', 'XML External Entity'), ('rce', 'Remote Code Execution'), ('lfi', 'Local File Inclusion'), ('rfi', 'Remote File Inclusion'), ('open_redirect', 'Open Redirect'), ('ssrf', 'Server-Side Request Forgery'), ('info_disclosure', 'Information Disclosure'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('url', models.URLField(max_length=2048)),
                ('parameter', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.scan')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
    ]
