# Generated by Django 6.0.2 on 2026-02-11 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_add_advanced_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_id', models.CharField(help_text='Engine identifier', max_length=100)),
                ('engine_name', models.CharField(help_text='Human-readable engine name', max_length=255)),
                ('engine_category', models.CharField(choices=[('sast', 'SAST'), ('dast', 'DAST'), ('sca', 'SCA'), ('secrets', 'Secrets'), ('container', 'Container'), ('cloud', 'Cloud'), ('custom', 'Custom')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(default=0.0, help_text='Execution time in seconds')),
                ('findings_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('engine_config', models.JSONField(blank=True, default=dict, help_text='Configuration used for this engine')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_id', models.CharField(max_length=100)),
                ('engine_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence level 0.0-1.0')),
                ('file_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('cwe_id', models.CharField(blank=True, help_text='CWE ID', max_length=20, null=True)),
                ('cve_id', models.CharField(blank=True, help_text='CVE ID', max_length=50, null=True)),
                ('owasp_category', models.CharField(blank=True, max_length=100, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('finding_hash', models.CharField(blank=True, help_text='Hash for deduplication', max_length=64, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('fixed', 'Fixed'), ('accepted', 'Accepted Risk')], default='new', max_length=20)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_path', models.CharField(help_text='Path or URL to scan', max_length=2048)),
                ('target_type', models.CharField(choices=[('path', 'File Path'), ('url', 'URL'), ('git', 'Git Repository')], default='path', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(default=0.0, help_text='Total execution time in seconds')),
                ('enabled_engines', models.JSONField(blank=True, default=list, help_text='List of engine IDs that were enabled for this scan')),
                ('engine_categories', models.JSONField(blank=True, default=list, help_text='Engine categories used (sast, dast, sca, secrets, etc.)')),
                ('parallel_execution', models.BooleanField(default=True)),
                ('max_workers', models.IntegerField(default=4)),
                ('total_engines_run', models.IntegerField(default=0)),
                ('successful_engines', models.IntegerField(default=0)),
                ('failed_engines', models.IntegerField(default=0)),
                ('total_findings', models.IntegerField(default=0)),
                ('findings_by_severity', models.JSONField(blank=True, default=dict, help_text='Count of findings by severity level')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict, help_text='Configuration used for this scan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='scanner_vul_risk_sc_b879c5_idx',
            old_name='scanner_vul_risk_sc_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='scanner_vul_verifie_aab60f_idx',
            old_name='scanner_vul_verifie_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='scanner_vul_false_p_3e73b7_idx',
            old_name='scanner_vul_false_p_idx',
        ),
        migrations.AddField(
            model_name='enginefinding',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='scanner.enginefinding'),
        ),
        migrations.AddField(
            model_name='enginefinding',
            name='engine_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.engineexecution'),
        ),
        migrations.AddIndex(
            model_name='enginescan',
            index=models.Index(fields=['status'], name='scanner_eng_status_6b1bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='enginescan',
            index=models.Index(fields=['started_at'], name='scanner_eng_started_6208ec_idx'),
        ),
        migrations.AddIndex(
            model_name='enginescan',
            index=models.Index(fields=['target_type'], name='scanner_eng_target__d75a1d_idx'),
        ),
        migrations.AddField(
            model_name='enginefinding',
            name='engine_scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.enginescan'),
        ),
        migrations.AddField(
            model_name='engineexecution',
            name='engine_scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_executions', to='scanner.enginescan'),
        ),
        migrations.AddIndex(
            model_name='enginefinding',
            index=models.Index(fields=['severity'], name='scanner_eng_severit_a5cf71_idx'),
        ),
        migrations.AddIndex(
            model_name='enginefinding',
            index=models.Index(fields=['finding_hash'], name='scanner_eng_finding_86652b_idx'),
        ),
        migrations.AddIndex(
            model_name='enginefinding',
            index=models.Index(fields=['status'], name='scanner_eng_status_961646_idx'),
        ),
        migrations.AddIndex(
            model_name='enginefinding',
            index=models.Index(fields=['engine_id'], name='scanner_eng_engine__9f2453_idx'),
        ),
        migrations.AddIndex(
            model_name='enginefinding',
            index=models.Index(fields=['cwe_id'], name='scanner_eng_cwe_id_98c77d_idx'),
        ),
        migrations.AddIndex(
            model_name='engineexecution',
            index=models.Index(fields=['engine_id'], name='scanner_eng_engine__05fa04_idx'),
        ),
        migrations.AddIndex(
            model_name='engineexecution',
            index=models.Index(fields=['status'], name='scanner_eng_status_cc8019_idx'),
        ),
        migrations.AddIndex(
            model_name='engineexecution',
            index=models.Index(fields=['engine_category'], name='scanner_eng_engine__36f445_idx'),
        ),
    ]
