# Generated by Django 6.0.2 on 2026-02-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_engineexecution_enginefinding_enginescan_and_more'),
        ('scanner', '0004_rename_scanner_vul_risk_sc_idx_scanner_vul_risk_sc_b879c5_idx_and_more'),
    ]

    operations = [
    ]
