# Generated by Django 6.0.2 on 2026-02-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_engineexecution_enginefinding_enginescan_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='scanner_vul_risk_sc_b879c5_idx',
            old_name='scanner_vul_risk_sc_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='scanner_vul_verifie_aab60f_idx',
            old_name='scanner_vul_verifie_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='scanner_vul_false_p_3e73b7_idx',
            old_name='scanner_vul_false_p_idx',
        ),
    ]
