# Generated by Django 6.0.2 on 2026-03-02 05:04
#
# NOTE: RenameIndex operations have been removed from this migration.
# AddField operations replaced with idempotent RunSQL to handle columns
# that may already exist in the database.
#
# RATIONALE:
# -----------
# This migration originally contained RenameIndex operations for indexes on
# ExploitMedia and Vulnerability models:
#   - scanner_exploitmedia_vuln_seq_idx -> scanner_exp_vulnera_1eff1f_idx
#   - scanner_exploitmedia_type_idx     -> scanner_exp_media_t_2ddbb3_idx
#   - scanner_vul_risk_sc_idx           -> scanner_vul_risk_sc_b879c5_idx
#   - scanner_vul_verifie_idx           -> scanner_vul_verifie_aab60f_idx
#   - scanner_vul_false_p_idx           -> scanner_vul_false_p_3e73b7_idx
#
# These were removed because index renames can fail in environments where:
#   - Old indexes don't exist in fresh installations
#   - Indexes were already renamed or dropped in earlier migrations
#   - Migrations were applied in different orders across environments
#   - Database schema was modified outside of Django migrations
#
# The AddField operations were replaced with idempotent RunSQL because:
#   - The columns may already exist from a partially-applied migration
#   - Using IF NOT EXISTS prevents DuplicateColumn errors
#   - This is safe on both fresh databases and existing ones

from django.db import migrations, models

def _add_column_if_missing(table, column, col_type, default=None):
    """Return RunSQL that adds a column only when it does not already exist."""
    default_clause = "" if default is None else f" DEFAULT {default}"
    return migrations.RunSQL(
        sql=f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                      FROM information_schema.columns
                     WHERE table_name = '{table}'
                       AND column_name = '{column}'
                ) THEN
                    ALTER TABLE "{table}" ADD COLUMN "{column}" {col_type}{default_clause};
                END IF;
            END$$;
        """,
        reverse_sql=f'ALTER TABLE "{table}" DROP COLUMN IF EXISTS "{column}";',
        state_operations=[
            migrations.AddField(
                model_name=table.split('_', 1)[1],
                name=column,
                field=_get_field(column),
            ),
        ],
    )

def _get_field(column_name):
    """Return the Django model field definition for the given column."""
    if column_name == 'poc_html_report_path':
        return models.CharField(
            blank=True,
            help_text='Path to the generated self-contained HTML PoC report',
            max_length=512,
            null=True,
        )
    elif column_name == 'poc_step_count':
        return models.IntegerField(
            default=0,
            help_text='Number of completed PoC exploitation steps',
        )
    elif column_name == 'poc_steps_json':
        return models.TextField(
            blank=True,
            help_text='JSON array of step-by-step proof-of-concept exploitation data',
            null=True,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_add_bounty_report'),
    ]

    operations = [
        # RenameIndex operations removed - see top-of-file comments.

        # Idempotent column additions — safe whether columns exist or not.
        _add_column_if_missing(
            'scanner_vulnerability',
            'poc_html_report_path',
            'varchar(512) NULL',
        ),
        _add_column_if_missing(
            'scanner_vulnerability',
            'poc_step_count',
            'integer NOT NULL',
            default='0',
        ),
        _add_column_if_missing(
            'scanner_vulnerability',
            'poc_steps_json',
            'text NULL',
        ),
    ]
