# Generated by Django 6.0.2 on 2026-03-02 05:04
#
# NOTE: RenameIndex operations have been removed from this migration.
#
# RATIONALE:
# -----------
# This migration originally contained RenameIndex operations for indexes on
# ExploitMedia and Vulnerability models:
#   - scanner_exploitmedia_vuln_seq_idx -> scanner_exp_vulnera_1eff1f_idx
#   - scanner_exploitmedia_type_idx     -> scanner_exp_media_t_2ddbb3_idx
#   - scanner_vul_risk_sc_idx           -> scanner_vul_risk_sc_b879c5_idx
#   - scanner_vul_verifie_idx           -> scanner_vul_verifie_aab60f_idx
#   - scanner_vul_false_p_idx           -> scanner_vul_false_p_3e73b7_idx
#
# These were removed because index renames can fail in environments where:
#   - Old indexes don't exist in fresh installations
#   - Indexes were already renamed or dropped in earlier migrations
#   - Migrations were applied in different orders across environments
#   - Database schema was modified outside of Django migrations
#
# This follows the best practice established in migration 0005_safe_index_rename.py,
# which documents that index renames are problematic and should be avoided.
# See 0005_safe_index_rename.py for full rationale and troubleshooting guidance.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_add_bounty_report'),
    ]

    operations = [
        # RenameIndex operations removed - see comments at top of file for rationale.
        migrations.AddField(
            model_name='vulnerability',
            name='poc_html_report_path',
            field=models.CharField(blank=True, help_text='Path to the generated self-contained HTML PoC report', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='poc_step_count',
            field=models.IntegerField(default=0, help_text='Number of completed PoC exploitation steps'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='poc_steps_json',
            field=models.TextField(blank=True, help_text='JSON array of step-by-step proof-of-concept exploitation data', null=True),
        ),
    ]
