# Generated by Django 6.0.2 on 2026-03-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_add_bounty_report'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exploitmedia',
            new_name='scanner_exp_vulnera_1eff1f_idx',
            old_name='scanner_exploitmedia_vuln_seq_idx',
        ),
        migrations.RenameIndex(
            model_name='exploitmedia',
            new_name='scanner_exp_media_t_2ddbb3_idx',
            old_name='scanner_exploitmedia_type_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='scanner_vul_risk_sc_b879c5_idx',
            old_name='scanner_vul_risk_sc_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='scanner_vul_verifie_aab60f_idx',
            old_name='scanner_vul_verifie_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='scanner_vul_false_p_3e73b7_idx',
            old_name='scanner_vul_false_p_idx',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='poc_html_report_path',
            field=models.CharField(blank=True, help_text='Path to the generated self-contained HTML PoC report', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='poc_step_count',
            field=models.IntegerField(default=0, help_text='Number of completed PoC exploitation steps'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='poc_steps_json',
            field=models.TextField(blank=True, help_text='JSON array of step-by-step proof-of-concept exploitation data', null=True),
        ),
    ]
