# Generated by Django 6.0.2 on 2026-02-03 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='Target domain or URL', max_length=500)),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('wayback_urls', models.TextField(blank=True, help_text='JSON array of Wayback Machine URLs')),
                ('shodan_data', models.TextField(blank=True, help_text='JSON data from Shodan API')),
                ('hunter_data', models.TextField(blank=True, help_text='JSON data from Hunter.io API')),
                ('dork_queries', models.TextField(blank=True, help_text='JSON array of Google Dorks')),
                ('total_urls', models.IntegerField(default=0)),
                ('total_emails', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OSINT Scan',
                'verbose_name_plural': 'OSINT Scans',
                'ordering': ['-scan_date'],
            },
        ),
    ]
