# Generated by Django 6.0.2 on 2026-02-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='high_risk_findings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='sensitive_scan_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='sensitive_scan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='total_findings',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SensitiveFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('finding_type', models.CharField(max_length=100)),
                ('value', models.TextField(help_text='The actual sensitive data found')),
                ('context', models.TextField(help_text='Surrounding text for context')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20)),
                ('position', models.IntegerField(blank=True, help_text='Position in content', null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('false_positive', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_findings', to='discover.scan')),
            ],
            options={
                'verbose_name': 'Sensitive Finding',
                'verbose_name_plural': 'Sensitive Findings',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['scan', 'severity'], name='discover_se_scan_id_2b62a7_idx'), models.Index(fields=['finding_type'], name='discover_se_finding_ed62c6_idx')],
            },
        ),
    ]
