# Generated by Django 6.0.2 on 2026-02-12 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_scan_dork_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('layout_config', models.TextField(help_text='JSON configuration for dashboard layout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScanRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_target', models.CharField(max_length=500)),
                ('reason', models.TextField(help_text='Why this target is recommended')),
                ('confidence_score', models.FloatField(default=0.0, help_text='ML confidence score 0-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Scan Recommendation',
                'verbose_name_plural': 'Scan Recommendations',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('scan_start', 'Scan Started'), ('scan_view', 'Scan Viewed'), ('finding_verify', 'Finding Verified'), ('finding_false_positive', 'Finding Marked False Positive'), ('export_data', 'Data Exported'), ('dashboard_view', 'Dashboard Viewed')], max_length=50)),
                ('target', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.TextField(blank=True, help_text='Additional JSON metadata')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='scan_duration_seconds',
            field=models.IntegerField(default=0, help_text='Duration of the scan'),
        ),
        migrations.AddField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discover_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['-scan_date'], name='discover_sc_scan_da_0b2745_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['target'], name='discover_sc_target_1383f1_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['user', '-scan_date'], name='discover_sc_user_id_b53bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivefinding',
            index=models.Index(fields=['-discovered_at'], name='discover_se_discove_896d8d_idx'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanrecommendation',
            name='based_on_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discover.scan'),
        ),
        migrations.AddField(
            model_name='scanrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='discover.scan'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scanrecommendation',
            index=models.Index(fields=['user', '-created_at'], name='discover_sc_user_id_c0cc57_idx'),
        ),
        migrations.AddIndex(
            model_name='scanrecommendation',
            index=models.Index(fields=['-confidence_score'], name='discover_sc_confide_53047e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['-timestamp'], name='discover_us_timesta_37c174_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-timestamp'], name='discover_us_user_id_e6c707_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action'], name='discover_us_action_8bcca0_idx'),
        ),
    ]
