# Generated by Django 6.0.1 on 2026-02-03 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('xss', 'Cross-Site Scripting (XSS)'), ('sqli', 'SQL Injection'), ('csrf', 'Cross-Site Request Forgery'), ('idor', 'Insecure Direct Object Reference'), ('lfi', 'Local File Inclusion'), ('rfi', 'Remote File Inclusion'), ('rce', 'Remote Code Execution'), ('xxe', 'XML External Entity'), ('ssrf', 'Server-Side Request Forgery'), ('open_redirect', 'Open Redirect'), ('path_traversal', 'Path Traversal'), ('command_injection', 'Command Injection'), ('other', 'Other')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], db_index=True, default='medium', max_length=20)),
                ('target_url', models.URLField(db_index=True, max_length=2048)),
                ('payload', models.TextField(help_text='The payload that triggered the vulnerability')),
                ('request_method', models.CharField(default='GET', max_length=10)),
                ('request_headers', models.TextField(blank=True, help_text='JSON or text representation of request headers')),
                ('request_body', models.TextField(blank=True, help_text='Request body/parameters')),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.TextField(blank=True, help_text='JSON or text representation of response headers')),
                ('response_body', models.TextField(blank=True, help_text='Response body text')),
                ('evidence_html', models.TextField(blank=True, help_text='Full HTML response for inspection in iframe')),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or analysis')),
                ('endpoint', models.CharField(blank=True, db_index=True, help_text='Normalized endpoint path for grouping', max_length=500)),
                ('is_confirmed', models.BooleanField(db_index=True, default=False, help_text='Whether the vulnerability has been manually confirmed')),
                ('false_positive', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['attack_type', 'target_url'], name='response_an_attack__a8004b_idx'), models.Index(fields=['attack_type', 'endpoint'], name='response_an_attack__953044_idx'), models.Index(fields=['severity', 'detected_at'], name='response_an_severit_b4aaed_idx')],
            },
        ),
    ]
