# Generated by Django 6.0.1 on 2026-02-02 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('urls_discovered', models.IntegerField(default=0)),
                ('urls_crawled', models.IntegerField(default=0)),
                ('hidden_content_found', models.IntegerField(default=0)),
                ('inference_results', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SpiderTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_depth', models.IntegerField(default=3, help_text='Maximum crawl depth')),
                ('follow_external_links', models.BooleanField(default=False)),
                ('use_dirbuster', models.BooleanField(default=True)),
                ('use_nikto', models.BooleanField(default=True)),
                ('use_wikto', models.BooleanField(default=True)),
                ('enable_brute_force', models.BooleanField(default=True)),
                ('enable_inference', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferredContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='URL from which inference was made', max_length=2048)),
                ('inferred_url', models.URLField(help_text='Inferred/predicted URL', max_length=2048)),
                ('inference_type', models.CharField(choices=[('pattern', 'Pattern-based'), ('naming', 'Naming Convention'), ('version', 'Version Discovery'), ('technology', 'Technology Stack'), ('structure', 'Site Structure')], max_length=50)),
                ('confidence', models.FloatField(help_text='Confidence score 0-1')),
                ('reasoning', models.TextField(help_text='Why this inference was made')),
                ('verified', models.BooleanField(default=False)),
                ('exists', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferred_content', to='spider.spidersession')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiddenContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('content_type', models.CharField(choices=[('directory', 'Directory'), ('file', 'File'), ('api_endpoint', 'API Endpoint'), ('backup', 'Backup File'), ('config', 'Configuration File'), ('admin_panel', 'Admin Panel'), ('test_file', 'Test/Debug File'), ('other', 'Other')], max_length=50)),
                ('discovery_method', models.CharField(max_length=50)),
                ('status_code', models.IntegerField()),
                ('content_sample', models.TextField(blank=True, help_text='Sample of content found', null=True)),
                ('risk_level', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_content', to='spider.spidersession')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.AddField(
            model_name='spidersession',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='spider.spidertarget'),
        ),
        migrations.CreateModel(
            name='ToolScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(choices=[('dirbuster', 'DirBuster'), ('nikto', 'Nikto'), ('wikto', 'Wikto')], max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('findings_count', models.IntegerField(default=0)),
                ('raw_output', models.TextField(blank=True, help_text='Raw tool output', null=True)),
                ('parsed_results', models.JSONField(blank=True, help_text='Parsed/structured results', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_results', to='spider.spidersession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('discovery_method', models.CharField(choices=[('crawl', 'Web Crawling'), ('dirbuster', 'DirBuster'), ('nikto', 'Nikto'), ('wikto', 'Wikto'), ('brute_force', 'Brute Force'), ('inference', 'Content Inference')], max_length=50)),
                ('depth', models.IntegerField(default=0)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Content not linked from main site')),
                ('is_interesting', models.BooleanField(default=False, help_text='Potentially interesting endpoint')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_urls', to='spider.spidersession')),
            ],
            options={
                'ordering': ['-discovered_at'],
                'unique_together': {('session', 'url')},
            },
        ),
        migrations.CreateModel(
            name='BruteForceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(max_length=2048)),
                ('path_tested', models.CharField(max_length=500)),
                ('full_url', models.URLField(max_length=2048)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False, help_text='Path exists (200-399 status)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brute_force_attempts', to='spider.spidersession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'success'], name='spider_brut_session_5e64c4_idx')],
            },
        ),
    ]
