# Generated by Django 6.0.1 on 2026-02-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidersession',
            name='parameters_discovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spidertarget',
            name='enable_parameter_discovery',
            field=models.BooleanField(default=True, help_text='Discover hidden parameters'),
        ),
        migrations.CreateModel(
            name='DiscoveredParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2048)),
                ('parameter_name', models.CharField(max_length=255)),
                ('parameter_value', models.CharField(max_length=255)),
                ('parameter_type', models.CharField(choices=[('debug', 'Debug Parameter'), ('test', 'Test Parameter'), ('admin', 'Admin Parameter'), ('developer', 'Developer Parameter'), ('feature_flag', 'Feature Flag'), ('other', 'Other')], max_length=50)),
                ('http_method', models.CharField(max_length=10)),
                ('discovery_evidence', models.TextField(help_text='Evidence of parameter effect')),
                ('risk_level', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('reveals_debug_info', models.BooleanField(default=False)),
                ('reveals_source_code', models.BooleanField(default=False)),
                ('reveals_hidden_content', models.BooleanField(default=False)),
                ('enables_functionality', models.BooleanField(default=False)),
                ('causes_error', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_parameters', to='spider.spidersession')),
            ],
            options={
                'ordering': ['-discovered_at'],
                'unique_together': {('session', 'target_url', 'parameter_name', 'parameter_value')},
            },
        ),
        migrations.CreateModel(
            name='ParameterBruteForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_value', models.CharField(max_length=500)),
                ('test_description', models.CharField(help_text='Description of what was tested', max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False, help_text='Test revealed something interesting')),
                ('finding_description', models.TextField(blank=True, help_text='What was found', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovered_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brute_force_attempts', to='spider.discoveredparameter')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_brute_force', to='spider.spidersession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['discovered_parameter', 'success'], name='spider_para_discove_cff272_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParameterDiscoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2048)),
                ('parameter_name', models.CharField(max_length=255)),
                ('parameter_value', models.CharField(max_length=255)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10)),
                ('parameter_location', models.CharField(choices=[('query', 'Query String'), ('body', 'Request Body'), ('both', 'Both Query & Body')], max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('response_diff', models.BooleanField(default=False, help_text='Response differs from baseline')),
                ('behavior_changed', models.BooleanField(default=False, help_text='Application behavior changed')),
                ('error_revealed', models.BooleanField(default=False, help_text='Error or debug info revealed')),
                ('content_revealed', models.BooleanField(default=False, help_text='New content revealed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_attempts', to='spider.spidersession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'response_diff'], name='spider_para_session_78eaf8_idx'), models.Index(fields=['session', 'behavior_changed'], name='spider_para_session_bc4b2d_idx')],
            },
        ),
    ]
