# Generated by Django 6.0.1 on 2026-02-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_spidersession_parameters_discovered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidertarget',
            name='enable_stealth_mode',
            field=models.BooleanField(default=True, help_text='Enable stealth features to avoid detection'),
        ),
        migrations.AddField(
            model_name='spidertarget',
            name='stealth_delay_max',
            field=models.FloatField(default=3.0, help_text='Maximum delay between requests in seconds'),
        ),
        migrations.AddField(
            model_name='spidertarget',
            name='stealth_delay_min',
            field=models.FloatField(default=1.0, help_text='Minimum delay between requests in seconds'),
        ),
        migrations.AddField(
            model_name='spidertarget',
            name='use_random_user_agents',
            field=models.BooleanField(default=True, help_text='Rotate user agents between requests'),
        ),
    ]
