# Generated by Django 6.0.2 on 2026-02-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_spidertarget_enable_stealth_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidertarget',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of retry attempts for failed requests'),
        ),
        migrations.AddField(
            model_name='spidertarget',
            name='request_timeout',
            field=models.IntegerField(default=30, help_text='Request timeout in seconds'),
        ),
    ]
