# Generated by Django 6.0.4 on 2026-04-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_add_request_timeout_and_max_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidertarget',
            name='enable_adaptive_stealth',
            field=models.BooleanField(default=True, help_text='Automatically adjust stealth settings based on target behavior'),
        ),
        migrations.AddField(
            model_name='spidertarget',
            name='max_parameter_tests',
            field=models.IntegerField(default=100, help_text='Maximum number of parameter discovery attempts per URL (cap to prevent combinatorial explosion)'),
        ),
    ]
